# Generated by Django 3.0.3 on 2020-04-04 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=100)),
                ('Product', models.CharField(max_length=100)),
                ('Prod_id', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField()),
                ('card_number', models.CharField(max_length=100)),
                ('Name_on_card', models.CharField(max_length=100)),
                ('cvv', models.IntegerField()),
                ('Date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 4, 11, 56, 33, 633014))),
            ],
        ),
    ]
