# Generated by Django 3.0.3 on 2020-04-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prodmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Prod_id', models.CharField(max_length=20)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Specification', models.CharField(max_length=200)),
                ('Status', models.CharField(choices=[('Available', 'Available'), ('Sold Out', 'Sold Out')], default='Available', max_length=20)),
                ('Pictures', models.FileField(blank=True, null=True, upload_to='pictures')),
                ('Eqipment', models.CharField(blank=True, choices=[('Dumbles', 'Dumbles'), ('Trademill', 'Trademill'), ('Elliptical Trainer', 'Elliptical Trainer'), ('Bikes', 'Bikes'), ('Rowers', 'Rowers')], default='Available', max_length=20, null=True)),
            ],
        ),
    ]
